# Generated by Django 4.0.6 on 2022-11-05 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.device')),
                ('state', models.BooleanField()),
                ('mqtt_topic', models.CharField(max_length=100)),
                ('has_white_led', models.BooleanField()),
                ('r', models.PositiveSmallIntegerField()),
                ('g', models.PositiveSmallIntegerField()),
                ('b', models.PositiveSmallIntegerField()),
                ('w', models.PositiveSmallIntegerField()),
            ],
            bases=('backend.device',),
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.device')),
                ('state', models.BooleanField()),
                ('mqtt_topic', models.CharField(max_length=100)),
            ],
            bases=('backend.device',),
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.room'),
        ),
    ]
