# Generated by Django 4.0.6 on 2023-01-02 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_sensor_alter_switch_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='humidity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pressure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='Thermostat',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.device')),
                ('state', models.BooleanField()),
                ('mqtt_topic', models.CharField(max_length=100)),
                ('target_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rel_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sensor')),
            ],
            bases=('backend.device',),
        ),
    ]
