# Generated by Django 4.0.10 on 2023-05-25 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_sensor_humidity_alter_sensor_pressure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.device')),
                ('state', models.BooleanField()),
                ('speed', models.PositiveSmallIntegerField()),
                ('mqtt_topic', models.CharField(max_length=100)),
            ],
            bases=('backend.device',),
        ),
    ]
