# Generated by Django 4.0.10 on 2023-06-02 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_fan_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.device')),
                ('state', models.BooleanField()),
                ('mqtt_topic', models.CharField(max_length=100)),
            ],
            bases=('backend.device',),
        ),
    ]
